### ISSUE TITLE
wrong port names after rock-convert

### ISSUE THREAD

**Issue by annaborn** [rock-core/tools-log_tools#2]
After conversion of the log file with the `rock-convert`command, the output ports have wrong names.
E.g. in `rock-replay` the original log file contains:

```
Task:
    127.0.0.1/odometry
OutputPorts:
    odometry_delta_samples
    odometry_samples
    state
    transformer_status
    transformer_stream_aligner_status
```

The converted log file contains:

```
Task:
    127.0.0.1/odometry
OutputPorts:
    0.0.1/odometry.odometry_delta_samples
    0.0.1/odometry.odometry_samples
    0.0.1/odometry.state
    0.0.1/odometry.transformer_status
    0.0.1/odometry.transformer_stream_aligner_status
```

Moreover, if I try to access one of the ports in the converted log file, e.g. to visualize the data on the port `odometry_samples` in vizkit, the following error message comes:

```
orocos.rb[WARN]: task 127.0.0.1/odometry has currently no port called 0
/home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/tools/orocos.rb/lib/orocos/async/object_base.rb:350:in `block (2 levels) in wait': Orocos::Async::PortProxy: 127.0.0.1/odometry.0 is not reachable after 5.0 seconds (Orocos::NotFound)
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/tools/orocos.rb/lib/orocos/async/object_base.rb:349:in `block in wait'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/tools/orocos.rb/lib/orocos/async/object_base.rb:347:in `wait'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/tools/orocos.rb/lib/orocos/async/log/ports.rb:96:in `to_proxy'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/gui/vizkit/lib/vizkit/vizkit_items.rb:962:in `port_from_items'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/gui/vizkit/lib/vizkit/vizkit_items.rb:478:in `context_menu'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/gui/vizkit/lib/vizkit/tree_view.rb:15:in `block in setup_tree_view'
    from /usr/lib/ruby/vendor_ruby/1.9.1/Qt/qtruby4.rb:2427:in `call'
    from /usr/lib/ruby/vendor_ruby/1.9.1/Qt/qtruby4.rb:2427:in `invoke'
    from /usr/lib/ruby/vendor_ruby/1.9.1/Qt/qtruby4.rb:469:in `qt_metacall'
    from /usr/lib/ruby/vendor_ruby/1.9.1/Qt/qtruby4.rb:469:in `method_missing'
    from /usr/lib/ruby/vendor_ruby/1.9.1/Qt/qtruby4.rb:469:in `exec'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/gui/vizkit/lib/vizkit/vizkit.rb:137:in `exec'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/gui/vizkit/bin/rock-replay:105:in `replay'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/gui/vizkit/bin/rock-replay:150:in `<main>'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/tools/utilrb/lib/utilrb/event_loop.rb:622:in `step'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/tools/utilrb/lib/utilrb/event_loop.rb:521:in `exec'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/tools/utilrb/lib/utilrb/event_loop.rb:541:in `wait_for'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/tools/orocos.rb/lib/orocos/async/object_base.rb:347:in `wait'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/tools/orocos.rb/lib/orocos/async/log/ports.rb:96:in `to_proxy'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/gui/vizkit/lib/vizkit/vizkit_items.rb:962:in `port_from_items'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/gui/vizkit/lib/vizkit/vizkit_items.rb:478:in `context_menu'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/gui/vizkit/lib/vizkit/tree_view.rb:15:in `block in setup_tree_view'
    from /usr/lib/ruby/vendor_ruby/1.9.1/Qt/qtruby4.rb:2427:in `call'
    from /usr/lib/ruby/vendor_ruby/1.9.1/Qt/qtruby4.rb:2427:in `invoke'
    from /usr/lib/ruby/vendor_ruby/1.9.1/Qt/qtruby4.rb:469:in `qt_metacall'
    from /usr/lib/ruby/vendor_ruby/1.9.1/Qt/qtruby4.rb:469:in `method_missing'
    from /usr/lib/ruby/vendor_ruby/1.9.1/Qt/qtruby4.rb:469:in `exec'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/gui/vizkit/lib/vizkit/vizkit.rb:137:in `exec'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/gui/vizkit/bin/rock-replay:105:in `replay'
    from /home/dfki.uni-bremen.de/aborn/DFKI/LIMES/ROCK_2015_02_10/gui/vizkit/bin/rock-replay:150:in `<main>'
```

**Comment by annaborn** [comment]
@D-Alex: could you please take a look at this issue? or maybe you could give me some tips what could be a reason for that?

**Comment by D-Alex** [comment]
The stream name is copied from the old one: https://github.com/rock-core/tools-log_tools/blob/master/lib/log_tools/converter.rb#L259. 

Therefore, I do not know why you get a wrong name in this case. Can you send me a small sample log file?

**Comment by D-Alex** [comment]
fixed on master
